Redis:

  Password: "g9#-n5ceWx8*&XG*"
  Host: "redismc.shrlk.systems"
  MaxConnections: 2
  Port: 25591
  TimeOut: 9000
  useTLS: false
  EncryptMessages: true
  EncryptionKey: "16CHARACTERS KEY"
  MacKey: "16CHARACTERS KEY"

#the channels from which this server can receive messages
#you can always send messages to all channels!
#you can add as many channels as you wish!
Channels:
  - "heartbeat"
  - "messages"
  - "sync"
  - "onlinenotif"
  - "update"
